services:
  - type: web
    name: olivia-whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: BOT_NAME
        value: Olivia
      - key: OWNER_NAME
        value: Subhash
      - key: MY_WEBSITE
        value: https://69studiobysubash.online/
      - key: COOLDOWN_MINUTES
        value: 10
      - key: USE_AI
        value: true
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_DATA
        sync: false
      - key: TZ
        value: Asia/Colombo
